//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsAndTravelSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelerQuestion
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public int AgencyId { get; set; }
        public int TravelerId { get; set; }
        public System.DateTime QuestionDate { get; set; }
        public System.DateTime AnswerDate { get; set; }
        public string Answer { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
