//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsAndTravelSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripsAndTravelDatabaseEntities : DbContext
    {
        public TripsAndTravelDatabaseEntities()
            : base("name=TripsAndTravelDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DislikedPost> DislikedPosts { get; set; }
        public virtual DbSet<FavoritePost> FavoritePosts { get; set; }
        public virtual DbSet<LikedPost> LikedPosts { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<TravelerQuestion> TravelerQuestions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
